name: Build Desktop Application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet fastapi uvicorn python-telegram-bot aiohttp python-multipart qrcode pillow pyinstaller
    
    - name: Install Node.js dependencies
      run: npm install
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "WhatsAppChecker" --add-data "whatsapp_server.js;." --add-data "api_server.py;." --add-data "telegram_bot.py;." --add-data "setup_dependencies.py;." --add-data "static;static" desktop_app.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: WhatsAppChecker-Windows
        path: dist/WhatsAppChecker.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet fastapi uvicorn python-telegram-bot aiohttp python-multipart qrcode pillow pyinstaller
    
    - name: Install Node.js dependencies
      run: npm install
    
    - name: Build executable
      run: |
        pyinstaller --onefile --name "WhatsAppChecker" --add-data "whatsapp_server.js:." --add-data "api_server.py:." --add-data "telegram_bot.py:." --add-data "setup_dependencies.py:." --add-data "static:static" desktop_app.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: WhatsAppChecker-Linux
        path: dist/WhatsAppChecker
        
